// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkURMvTtUfzuOwDblT1xTrMji7mKXoL9I',
    appId: '1:190068513759:web:e6ad8e625db271f24c826a',
    messagingSenderId: '190068513759',
    projectId: 'smart-attendance-app-157d9',
    authDomain: 'smart-attendance-app-157d9.firebaseapp.com',
    storageBucket: 'smart-attendance-app-157d9.firebasestorage.app',
    measurementId: 'G-J0DG27DDCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXu_ruWFI7RhB98mCEiscxd8vcDPg-_o',
    appId: '1:190068513759:android:c26a2486920967e64c826a',
    messagingSenderId: '190068513759',
    projectId: 'smart-attendance-app-157d9',
    storageBucket: 'smart-attendance-app-157d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkURMvTtUfzuOwDblT1xTrMji7mKXoL9I',
    appId: '1:190068513759:web:76fca53cfe8812634c826a',
    messagingSenderId: '190068513759',
    projectId: 'smart-attendance-app-157d9',
    authDomain: 'smart-attendance-app-157d9.firebaseapp.com',
    storageBucket: 'smart-attendance-app-157d9.firebasestorage.app',
    measurementId: 'G-M96Y789K9E',
  );
}
